void Cutscene::nathanMaryScript() {
  switch(sceneID) {
  case scene0:
    changeShowCharacter(protag);
    changeBackground(bgLivingRoom, 2);
    addL(none, "*clack*");
    addL(mom, "Oh, Nate, thank goodness you're here. Can you do me a favour?");
    addL(mom, "I forgot to buy eggs for today's supper. Can you go buy them for me?");
    // changeShowCharacter(protag, angryFace);
    addChoice(2, "Okay", "No");
    break;
  case scene0_2:
    changeShowCharacter(protag, angryFace);
    addL(nathan, "No.");
    addL(mom, "Then we're having omelettes without eggs for today's supper.");
    changeShowCharacter(protag, neutralFace);
    addL(nathan, ".........");
    break;
  case scene0_1:
    changeShowCharacter(protag);
    addL(nathan, "Okay.");
    changeBackground(bgStreet1, 2);
    addL(nathan, ".........");
    changeShowCharacter(mary, happyFace3, pX, pY, defpw, defph, 0, 1, 3);
    addL(mary, "Gooooooooooooooooood!");
    addL(nathan, ".........");
    addL(mary, "After!");
    addL(mary, "Noon!");
    changeShowCharacter(mary, happyFace2);
    addL(nathan, ".........");
    addL(nathan, "Who are you?");

    changeShowCharacter(mary, sadFace);
    /*addL(mary, "What?! I'm forgotten already?!");*/
    addL(mary, "It's Mary, Mary van Buren!\nWe sat next to each other yesterday!");
    addL(nathan, "Oh, right. Good morning.");
	changeShowCharacter(mary, happyFace2);
    addL(mary, "Well, well, now, there's no need to apologize. The school year did just start, after all. You'll have plenty of time to remember me.");
	addL(nathan, "I didn't apologize...");
    /*changeShowCharacter(mary, happyFace2);
    addL(mary, "Because I'm a kind person, I'm willing to forgive your outrageous lack of delicacy for the measly price of one Snickers bar.");
    addL(mary, "So, pay up.");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "No.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "Can you at least give a quarter? Then I can buy it at the vending machine.");
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "Is that enough to buy it?");
    addL(mary, "No, that's how much I'm short.");
	*/
    changeShowCharacter(protag, angryFace);
    addL(nathan, "Ah...");
	changeShowCharacter(mary, neutralFace);
    addL(mary, "What?");
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "I'm supposed to go to the grocery store now. I don't have time to talk to you.");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "In that case, we should go together!");
    addL(nathan, "Why?");
    changeShowCharacter(mary, happyFace);
    addL(mary, "I'm heading there too. We ran out of eggs, so my mom asked to buy more.");
	changeShowCharacter(mary, happyFace2);
    addL(mary, "And you? What are you going to buy?");
	addL(nathan, "Well, that's a coincidence. I was also going to buy...");
    addChoice(2, "Eggs", "Plastic model kit");
    break;
  case scene0_1_1:
    changeShowCharacter(protag);
    changeShowCharacter(mary, happyFace2, pX, pY, defpw, defph, 0);
    addL(nathan, "I was going to buy eggs as well.");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Perfect! Let's go together, then. I know a good store.");
    addL(nathan, "I'd rather not...");
    changeShowCharacter(mary, sadFace);
    addL(mary, "What? But it's such a nice day.");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "That's irrelevant.");
    addL(mary, "Please?");
    addL(nathan, ".........");
    addL(nathan, "Fine.");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Yay!");
    changeBackground(bgGrocery, 1);
    changeShowCharacter(mary, neutralFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0, 1, 1);
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Chicken... Beef... Bacon...");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "Oh, there it is! My favorite! Soy sauce-flavored ramen!");
    /*addL(nathan, ".........");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "I don't remember the last time I bought the other flavors.\nShoyu ramen is just better.");
    addL(mary, "For example, chicken ramen doesn't taste like chicken at all.\nI don't know why they named it that.");
    addL(nathan, ".........");
    addL(mary, "Bacon gets close to tasting like bacon, but not quite.");
    changeShowCharacter(mary, neutralFace2);
    addL(mary, "I don't like it. I think they call\n that the \'uncanny valley.\'");
    addL(nathan, ".........");
    addL(mary, "Beef is fine, I suppose. It's kind of neutral. I use the powder to make curry.");
    addL(nathan, ".........");*/
	addL(nathan, "Listen...");
	changeShowCharacter(mary, happyFace2);
    addL(mary, "Yes?");
    addL(nathan, "Didn't you say you were going to buy eggs?");
    changeShowCharacter(mary, surpriseFace);
    addL(mary, "Oh, right, sorry! I almost forgot!");
    addL(none, "*whisper* *whisper*");
	changeShowCharacter(mary, neutralFace);
	addL(none, "*whisper* What's going on? Is he picking on her? *whisper*");
	changeShowCharacter(mary, mairiFace);
	addL(none, "*whisper* *whisper*");
	changeShowCharacter(protag, angryFace);
    addL(nathan, "......");
	changeShowCharacter(mary, happyFace2);
    addL(mary, "D-Do you prefer the brown or white eggs?");
    addChoice(2, "White", "They're the same");
    break;
  case scene0_1_2:
    changeShowCharacter(protag);
    changeShowCharacter(mary, happyFace2, pX, pY, defpw, defph, 0);
    addL(nathan, "I'm looking for a new plastic model kit.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "You mean those miniature models of boats you assemble from little parts?");
    addL(nathan, "Yeah.");
    changeShowCharacter(mary, neutralFace2);
    addL(mary, "Do they sell those at the grocery store?");
    addL(nathan, "No.");
	changeShowCharacter(mary, sadFace);
    addL(mary, "How is that a coincidence?");
    addL(nathan, "It's not.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "That reminds me, have you heard of the new store that opened recently?");
    addL(nathan, "New store?");
	changeShowCharacter(mary, happyFace2);
    addL(mary, "Yes, I heard they sell all kinds of weird stuff there. They probably have plastic models too.");\
    addL(nathan, "Did you even go there yet?");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "No, but I will soon!");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Let's-a-go-go!");
	  
    changeBackground(bgStore, 2);
    changeShowCharacter(mary, happyFace, pX + defpw/10, pY, defpw, defph, 0, 1, 1);
    changeShowCharacter(protag, angryFace);
    addL(nathan, "That's the sketchiest store I've ever seen.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "Really? It looks pretty normal to me.");
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "Are you sure they sell plastic model kits here?");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "There's only one way to find out! Let's-a-go-go-in!");
	changeShowCharacter(protag, angryFace);
    addL(nathan, "Stop saying that.");

    changeBackground(bgStoreInside, 1);
    changeShowCharacter(mary, neutralFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0, 1, 1);
	changeShowCharacter(protag, neutralFace);
    addL(clerk, "Konnichiwelcome!");
    addL(nathan, "Er... good afternoon.");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "Good afternoon! Would you happen to sell any plastic model kits?");
    addL(clerk, "Yes!");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Great! Can we see them?");
    addL(clerk, "No!");
    changeShowCharacter(mary, sadFace);
    addL(mary, "...");
    addL(clerk, "I no understand English!");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "What language do you speak?");
    addL(clerk, "I no understand English!");
    changeShowCharacter(mary, sadFace);
    addL(mary, "What do we do?");
    addChoice(2, "Speak Spanish", "Use sign language");
    break;
  case scene0_1_2_1:
    changeShowCharacter(mary, neutralFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0, 1);
    changeShowCharacter(protag);
    addL(nathan, "Comprendes español?");
    addL(clerk, "O! Ho mal di stomaco!");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "Teño vinte años de experiencia en esquí!");
    addL(clerk, "Non è vero!");
    addL(nathan, "!");
    addL(clerk, "Sciocco!");
    changeShowCharacter(protag, angryFace2);
    addL(nathan, "Que dices!");
    addL(clerk, "Ho bisogno di lassativos!");
    changeShowCharacter(mary, sadFace);
    addL(mary, "I can't understand anything.");
    addL(nathan, "Infeliz, teño vinte años de experiencia en esquí!");
    addL(clerk, "Canaglia!");
    addL(nathan, "Te farei comer patacas!");
    addL(clerk, "Prende questo!");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "Ai!");
    changeShowCharacter(mary, surpriseFace);
    addL(mary, "Wait, why are you fighting?!");
    changeShowCharacter(protag, angryFace2);
    addL(nathan, "Ha!");
    addL(clerk, "Tropo lento!");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "Ui!");
    addL(clerk, "Ha! Ha! Ha!");
    changeShowCharacter(protag, angryFace2);
    addL(nathan, "É forte de máis! Resta-me unha opción!");
    addL(nathan, "Genki Dama!");
    addL(mary, "Wat in Godsnaam?!");
    break;
  case scene0_1_2_2:
    changeShowCharacter(mary, neutralFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0, 1);
    changeShowCharacter(protag);
    addL(nathan, "It's all right. I know sign language.");
	changeShowCharacter(mary, happyFace2);
    addL(mary, "Really? That's amazing!");
    addL(nathan, "[Good afternoon.]", false);
	changeShowCharacter(mary, happyFace);
    addL(clerk, "[Konnichiwelcome!]", false);
    addL(nathan, "[Do you sell plastic model kits?]", false);
    changeShowCharacter(mary, neutralFace2);
    addL(clerk, "[I cannot understand that sign.]", false);
    addL(nathan, "[I'll spell it.]", false);
    addL(nathan, "[P]", false);
    addL(nathan, "[L]", false);
    changeShowCharacter(mary, neutralFace);
    addL(nathan, "[A]", false);
    addL(nathan, "[S]", false);
    changeShowCharacter(mary, neutralFace2, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0, 1, 4);
    changeShowCharacter(mary, neutralFace2, (camera.w-defpw*0.75)/2 - defpw/7, (camera.h-defph*0.75)/2 + defph*0.75/5, defpw*0.75, defph*0.75, 0, 1, 3);
    addL(clerk, "[Just kidding, I got it the first time.]", false);
    addL(nathan, "[What kind of models do you have?]", false);
    addL(clerk, "[Frog]", false);
    changeShowCharacter(mary, neutralFace);
    addL(nathan, "[Sorry, I think misunderstood you.]", false);
    changeShowCharacter(mary, neutralFace2);
    addL(clerk, "[Frog]", false);
	addL(nathan, "[Sorry, I think misunderstood you.]", false);
	addL(clerk, "[Frog]", false);
    addL(nathan, "[What is the name of the first president of the United States?]", false);
    doAnim(mary, 1);
    addL(clerk, "[Frog]", false);
    addL(nathan, "[Which planet is closest to Earth?]", false);
    addL(clerk, "[Frog]", false);
    //doAnim(mary, 1);
    addL(nathan, "[What do you want to be when you grow up?]", false);
    //changeShowCharacter(mary, happyFace2);
    addL(clerk, "[Frog]", false);
    changeShowCharacter(protag, angryFace);
    changeShowCharacter(mary, happyFace2);
    addL(nathan, "(I don't know what he's saying...)");
    changeShowCharacter(mary, happyFace2, (camera.w-defpw*0.75)/2 - defpw/7, (camera.h-defph*0.75)/2 + defph*0.75/5, defpw*0.75, defph*0.75, 0, 1, 4);
    changeShowCharacter(mary, happyFace3, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0, 1, 3);
    addL(mary, "Look what I found! Isn't this plastic model of a frog cute?");
    changeShowCharacter(protag, angryFace2);
    addL(nathan, "What?!");
    break;
  case scene0_1_1_1:
    changeShowCharacter(protag);
    changeShowCharacter(mary, happyFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0);
    addL(nathan, "White.");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "Then I'll get the white ones, too.");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Good afternoon! I'd like to buy this stuff.");
    addL(clerk, "Cash or card?");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "Cash. Just a second.");
    doAnim(mary, 2);
    addL(none, "*fumble* *fumble*");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "Huh?");
    doAnim(mary, 2);
    addL(none, "*fumble* *fumble* *fumble*");
    changeShowCharacter(mary, surpriseFace);
    addL(mary, "Huh??");
    doAnim(mary, 2);
    addL(none, "*fumble* *fumble*\n*fumble* *fumble*");
	changeShowCharacter(mary, mairiFace);
    addL(nathan, "......");
    addChoice(2, "Help her out", "Stay quiet");
    break;
  case scene0_1_1_2:
    changeShowCharacter(protag);
    changeShowCharacter(mary, happyFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0);
    addL(nathan, "They're the same thing.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "That's why I'm asking.");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "That doesn't make sense.");
    addL(mary, "You're not making sense, either. They're clearly different colors.");
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "Do you pick the white or black pieces in chess?");
    changeShowCharacter(mary, happyFace);
    addL(mary, "White, of course. They have a strategical advantage since they move first.");
    addL(nathan, "Why do you know that?");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "My sister's a Grandmaster.");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "...Is that true?");
    changeShowCharacter(mary, neutralFace2);
    addL(mary, "She could be. When I play against her she always wins.");
	addL(nathan, "That doesn't sound difficult.");
	changeShowCharacter(mary, neutralFace);
    addL(mary, "???");
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "Never mind. We'll get the white eggs, then.");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Okay!");

    changeBackground(bgStreet2, 2);
    changeShowCharacter(mary, happyFace2, pX, pY, defpw, defph, 0, 1, 1);
    changeShowCharacter(protag, angryFace);
    addL(mary, "Look! Isn't the sunset beautiful?");
    addL(nathan, ".........");
    changeShowCharacter(mary, sadFace);
    addL(mary, "What's with the face?");
    addL(nathan, "That's just what my face looks like.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "Why are you making that expression?");
    addL(nathan, "Why are you making me carry twenty packets of soy sauce ramen?");
	changeShowCharacter(mary, sadFace);
    addL(mary, "I thought guys liked carrying stuff for girls?");
	addL(nathan, "Where on earth did you hear that...?");
    addL(mary, "Besides, didn't I tell you you can take two of them?");
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "I don't like soy sauce.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "Oh. Then I'll give you four.");

    addL(nathan, "That's the wrong operation.");
    changeShowCharacter(mary, sadFace);
    addL(mary, "One?");
    addL(nathan, "That's division.");
    changeShowCharacter(mary, happyFace);
    addL(mary, "Four.");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "That's what you just said.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "Well, what do you want that's not soy sauce ramen, then?");
    addChoice(2, "Give me a kiss", "Give me a tuna sandwich");
    break;
  case scene0_1_1_2_1:
    changeShowCharacter(protag);
    changeShowCharacter(mary, neutralFace, pX, pY, defpw, defph, 0, 1);
	addL(nathan, "Give me a kiss.");
	changeShowCharacter(mary, mairiFace);
    addL(mary, "What? No.");
	addL(nathan, "Well, that's what I thought.");
	changeShowCharacter(mary, neutralFace);
    addL(mary, "Do you want me to kiss you?");
	addL(nathan, "No.");
	changeShowCharacter(mary, sadFace);
	addL(mary, "Then why did you ask?");
	addL(nathan, "It seemed like the right thing to do.");
	changeShowCharacter(mary, neutralFace);
	addL(mary, "You're weird.");
	changeShowCharacter(protag, angryFace);
	addL(nathan, "I don't want to hear that from you.");
	changeShowCharacter(mary, happyFace2);
	addL(mary, "Weirdo.");
	addL(nathan, "...I'm going home.");
    /*addL(nathan, "All right. I want you to...");
    addL(nathan, ".........");
    addL(nathan, "I want you to go by \'Saucy Mol\' for a week.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "What's \'Mol?\'");
    addL(nathan,  "It's short for \'Mary.\'");
    addL(mary, "Oh, I see.");
    addL(nathan, "So when any stranger asks your name, you'll say 'Saucy Mol.'");
    changeShowCharacter(mary, happyFace);
    addL(mary, "Can I call you \'Sauceless Nat?\'");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "...No.");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "It's short for 'Jonathan.'");
    addL(nathan, "I didn't ask.");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "\'Sauceless Nat!\'");
    addL(nathan, "I'm going home.");
    changeShowCharacter(mary, surpriseFace);
    addL(mary, "Wait, Sauceless Nat! My ramen!");*/
    break;
  case scene0_1_1_2_2:
    changeShowCharacter(protag);
    changeShowCharacter(mary, neutralFace, pX, pY, defpw, defph, 0, 1);
    addL(nathan, "Give me a tuna sandwich.");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "Sure, what do you like in your sandwich? Mayonnaise?\nMustard? Mayonnaise?");
    addL(nathan, "...Caviar.");
    addL(mary, "What else?");
    addL(nathan, "Truffles.");
	addL(mary, "What else?");
    addL(nathan, "Gold flakes.");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Okay, I'll be back in a second!");
    changeShowCharacter(mary, happyFace3, pX, pY, defpw, defph, 0, 1, 2);
    addL(nathan, ".........");
    addL(nathan, ".........");
	addL(nathan, "She's joking... right?");
    break;
  case scene0_1_1_1_1:
    changeShowCharacter(protag);
    changeShowCharacter(mary, neutralFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0);
    addL(nathan, "Mary, you forgot to buy this.");
    addL(none, "............");
    addL(clerk, "Have a good afternoon!");
    changeBackground(bgStreet2, 2);
    changeShowCharacter(mary, sadFace, pX, pY, defpw, defph, 0, 1, 1);
    addL(mary, "Sigh... That was scary.");
	changeShowCharacter(protag, angryFace);
    addL(nathan, "Don't get used to it.");
    changeShowCharacter(mary, happyFace2);
    addL(mary, "I know, I know. I'll give you the money back next week.");
    changeShowCharacter(mary, neutralFace2);
    addL(mary, "Well, then, as thanks...");
	changeShowCharacter(mary, neutralFace);
	changeShowCharacter(protag, neutralFace);
    addL(nathan, "No, thanks.");
    changeShowCharacter(mary, sadFace);
    addL(mary, "What? But you don't even know what I'm going to give you yet.");
    addL(nathan, "I don't need to know.");
    changeShowCharacter(mary, neutralFace);
    addL(mary, "Well, I'll bet five dollars you can't guess what it is.");
    changeShowCharacter(mary, happyFace);
    addL(mary, "I'll give you a hint: you can't\nguess it.");
    addChoice(2, "It's a kiss", "It's a tuna sandwich");
    break;
  case scene0_1_1_1_2:
    changeShowCharacter(protag);
    changeShowCharacter(mary, mairiFace, (camera.w-defpw*1.25)/2, (camera.h-defph*1.25)/2 + defph*1.25/5, defpw*1.25, defph*1.25, 0);
    addL(nathan, ".........");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "A-ha-ha... it seems I forgot my wallet at home! Clumsy me!");
	changeShowCharacter(mary, happyFace2);
    addL(none, "*glance*");
    addL(nathan, ".........");
    addL(mary, ".........");
    addL(mary, "Er... Jonathan...");
    addL(nathan, "Who are you?");
    changeShowCharacter(mary, mairiFace);
    addL(mary, "Wha...");
    changeShowCharacter(protag, angryFace2);
    addL(nathan, "My name is not Jonathan! I have never met this woman in my life!");
	changeShowCharacter(mary, surpriseFace);
    addL(mary, "Jonathan!");
    addL(nathan, "Goodbye!");
    changeShowCharacter(mary, sadFace);
    addL(mary, "Wait, Jonathan! Where are you going? Wait!");
    break;
  case scene0_1_1_1_1_1:
    changeShowCharacter(mary, neutralFace, pX, pY, defpw, defph, 0);
	changeShowCharacter(protag);
    addL(nathan, "Were you going to kiss me?");
	changeShowCharacter(mary, mairiFace);
    addL(mary, "What? No, no. I wouldn't do that.");
    addL(nathan, "It's a joke.");
    addL(mary, "Is that so?");
	addL(mary, "......");
	changeShowCharacter(mary, neutralFace2);
	addL(mary, "Do you want to be kissed?");
	addL(nathan, "...Huh?");
	changeShowCharacter(mary, neutralFace);
	addL(mary, "Well, you know, would you like it if I...");
	addL(mary, "......");
	changeShowCharacter(mary, surpriseFace2);
    addL(mary, "N-Never mind! See you at school tomorrow!");
    addL(mary, "Thanks! Bye! Later!");
    changeShowCharacter(mary, neutralFace, pX, pY, defpw, defph, 0, 1, 2);
    changeShowCharacter(protag, neutralFace);
    addL(nathan, ".........");
	addL(nathan, ".........");
    addL(nathan, "Tomomorrow is Sunday...");
    /*changeShowCharacter(protag, angryFace2);
    addL(nathan, "I recognize this setup! You were going to kiss me just like in those corny old romance dramas!");
    addL(nathan, "A melodramatic track would play during the entire scene, while the two lovers confess their feelings to each other...");
    changeShowCharacter(protag, neutralFace);
    changeShowCharacter(mary, neutralFace);
    addL(nathan, "\'Extra Number One, I love you!\'");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "\'What took you so long, Extra Number Two? I love you, too!\'");
    changeShowCharacter(protag, neutralFace);
    changeShowCharacter(mary, happyFace);
    addL(nathan, "They draw each other into a loving embrace...");
    changeShowCharacter(mary, happyFace2);
    addL(nathan, "Then the credits roll as we stare at their black silhouettes outlined against the red–orange sunset...");
    changeShowCharacter(protag, angryFace2);
    addL(nathan, "Directed by Michael Bay.");
    changeShowCharacter(mary, happyFace3);
    addL(mary, "Bravo!");
    changeShowCharacter(mary, happyFace2);
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "Thanks.");
    changeShowCharacter(mary, happyFace);
    addL(mary, "...");
    changeShowCharacter(mary, neutralFace2);
    addL(mary, "...");
    addL(mary, "I don't mind it if it's on the cheek.");
    addL(nathan, ".........");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "What?");
    changeShowCharacter(protag, neutralFace);
    changeShowCharacter(mary, surpriseFace2);
    addL(mary, "N-Never mind! See you at school tomorrow!");
    addL(mary, "Thanks! Bye! Later!");
    changeShowCharacter(mary, neutralFace, pX, pY, defpw, defph, 0, 1, 2);
    changeShowCharacter(protag, neutralFace);
    addL(nathan, ".........");
    changeShowCharacter(protag, happyFace);
    addL(nathan, "The End.");*/
    break;
  case scene0_1_1_1_1_2:
    changeShowCharacter(mary, neutralFace, pX, pY, defpw, defph, 0);
    changeShowCharacter(protag, neutralFace);
    addL(nathan, "Is it a tuna sandwich?");
    changeShowCharacter(mary, surpriseFace);
    addL(mary, "What?! How did you know?!");
    addL(nathan, "I guessed.");
    addL(nathan, "You're a psychic!");
    addL(nathan, "No, I just guessed.");
    changeShowCharacter(mary, sadFace);
    addL(mary, "What am I thinking about right now?");
    addL(nathan, "......");
    addL(nathan, "Tuna sandwiches.");
    changeShowCharacter(mary, surpriseFace);
    addL(mary, "Jumping Jehosaphat!");
    changeShowCharacter(protag, angryFace);
    addL(nathan, "I'm going home.");
    break;
  }
}

void Cutscene::maryNathanScript() {
  switch(sceneID) {
  case scene0:
    changeShowCharacter(protag, happyFace2);
    changeBackground(bgLivingRoom, 2);
    addL(mary, "I'm back from school, Mom!");
    addL(mom, "Oh, Molly, thank goodness you're here. Can you do me a favour?");
    addL(mom, "I forgot to buy eggs for today's supper. Can you go buy them for me?");
    // changeShowCharacter(protag, angryFace);
    addChoice(2, "Sure", "No");
    break;
  case scene0_2:
    changeShowCharacter(protag, sadFace);
    addL(mary, "I don't want to.");
    addL(mom, "Then we're having omelettes without eggs for today's supper.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Okay!");
    addL(mary, "...");
    changeShowCharacter(protag, surpriseFace);
    addL(mary, "What?!");
    break;
  case scene0_1:
    changeShowCharacter(protag, happyFace3);
     changeShowCharacter(nathan, neutralFace2, cPX(0.75)-defpw/5, cPY(0.75), defpw*0.75, defph*0.75, 0, 0, -1);
    addL(mary, "Sure!");
    changeBackground(bgStreet1, 2);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "La-la-la! ♪\n Going to the grocery store! ♪\n In the sunshine! ♪");
    changeShowCharacter(nathan, neutralFace2, cPX(0.75)-defpw/5, cPY(0.75), defpw*0.75, defph*0.75, 0, 1, 5);
    changeShowCharacter(nathan, neutralFace2, cPX(0.75)-defpw/5, cPY(0.75), defpw*0.75, defph*0.75, 0, 1, 2);
    addL(mary, "Oh, it's Jonathan!");
    changeShowCharacter(nathan, neutralFace2, cPX(1), cPY(1), defpw, defph, 0, 1, 2);
    changeShowCharacter(nathan, neutralFace, cPX(1), cPY(1), defpw, defph, 0, 1, 3);
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Gooooooooooooooooood!");
    addL(mary, "After!");
    addL(mary, "Noon!");
    changeShowCharacter(protag, happyFace2);
    addL(nathan, ".........");
    changeShowCharacter(nathan, neutralFace2, cPX(1), cPY(1), defpw, defph, 0, 1, 2);
    changeShowCharacter(protag, mairiFace);
    addL(mary, "Wait! Don't just nod and walk away!");
    changeShowCharacter(nathan, neutralFace, cPX(1), cPY(1), defpw, defph, 0, 1, 3);
    addL(nathan, "Who are you?");
    changeShowCharacter(protag, surpriseFace);
    addL(mary, "What?! Have you forgotten me already?");
    addL(mary, "It's Mary, Mary van Buren! I'm your classmate!");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "You can't expect me to remember every single classmate's name. The school year's just begun.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "It started a month ago!");
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "Really?");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Because I'm a kind person, I'm willing to forgive your outrageous lack of delicacy for the measly price of one Snickers bar.");
    addL(mary, "So, pay up.");
    addL(nathan, "That's hardly a kind tone.");
    addL(mary, "Pay up, please.");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "Your English grades must be really low.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "That's rude. They're average, actually.");
    addL(nathan, "I don't believe it.");
    addL(mary, "Ask me any English-related question. I bet I can answer it.");
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "Who wrote 'Romeo and Juliet?'");
    addChoice(2, "Isaac Newton", "George Washington");
    break;
  case scene0_1_1:
    changeShowCharacter(protag, neutralFace);
    changeShowCharacter(nathan, neutralFace, cPX(), cPY(), defpw, defph, 0);
    addL(mary, "Isaac Newton?");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, ".......");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "Or was he the one who wrote 'Crime and Punishment?'");
    addL(nathan, ".......");
    changeShowCharacter(protag, sadFace);
    addL(mary, "Fine, I'll admit it. My grades are slightly below average.");
    
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "Shouldn't you be heading to the grocery store?");
    changeShowCharacter(protag, surpriseFace);
    addL(mary, "Great suffering catfish! How did you know?!");
    addL(nathan, "I heard you singing it. The grocery song.");
    changeShowCharacter(protag, mairiFace);
    addL(mary, "Geez, you heard that? That's embarrassing.");
    changeShowCharacter(protag, happyFace);
    addL(mary, "And you? Where are you going?");
    addL(nathan, "To the grocery store.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "What a coincidence! Let's go together, then!");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "I'd rather not...");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Let's-a-go-go!");
    
    changeBackground(bgGrocery, 1);
    changeShowCharacter(nathan, neutralFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Chicken... Beef... Bacon...");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Oh, there it is! My favorite! Soy sauce-flavored ramen!");
    addL(nathan, ".........");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "I don't remember the last time I bought the other flavors.\nSoy sauce is just better.");
    addL(mary, "For example, chicken ramen doesn't taste like chicken at all.\nI don't know why they named it that.");
    addL(nathan, ".........");
    addL(mary, "Bacon gets close to tasting like bacon, but not quite.");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "I don't like it. I think they call\n that the \'uncanny valley.\'");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, ".........");
    addL(nathan, "Are you here to buy eggs or instant noodles?");
    changeShowCharacter(protag, neutralFace);
    addChoice(2, "Eggs", "Ramen");
    break;
  case scene0_1_2:
    changeShowCharacter(protag, happyFace2);
    changeShowCharacter(nathan, neutralFace, cPX(), cPY(), defpw, defph, 0);
    addL(mary, "George Washington!");
    addL(nathan, "No, George Washington didn't produce any literature of note.");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "But it was pretty close, wasn't it?");
    addL(nathan, "No.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "But he was a great president.");
    addL(nathan, "That's not relevant.");
    addL(mary, "He freed the slaves.");
    /*addL(nathan, "That was Abraham Lincoln.");
    changeShowCharacter(protag, mairiFace);
    addL(mary, "Piers... P-Pake... Pearson...");
    changeShowCharacter(nathan, neutralFace);*/
    addL(nathan, "How many hours do you study a day?");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "About fifteen minutes?");
    addL(nathan, "Are you fine with that?");
    addL(mary, "Are you worried about me?");
    addL(nathan, "Of course I am. You're worse than my sister.");
    changeShowCharacter(protag, surpriseFace3);
    addL(mary, "You have a sister? Is she cute?");
    changeShowCharacter(nathan, neutralFace2);
    addL(nathan, "She's not cute.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "I'll go meet her now!");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "I said she's not cute!");
    
    changeBackground(bgLivingRoom, 2);
    changeShowCharacter(nathan, neutralFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Excuse me! Anyone at home?");
    addL(mom, "Oh, are you back already, Nate?");
    addL(mom, "My word, is that your girlfriend?");
    addChoice(2, "We're friends", "We've been dating for a month");
    break;
  case scene0_1_2_1:
    changeShowCharacter(protag, happyFace);
    changeShowCharacter(nathan, neutralFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    addL(mary, "We're friends.");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "Classmates.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "I came to your house, so that means we're friends now.");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "No, it doesn't.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "Why did you invite me to your house if you don't think of me as a friend?");
    addL(nathan, "I didn't invite you.");
    /*changeShowCharacter(protag, surpriseFace);
    addL(mary, "Wait, don't send me to jail! I'm sorry!");
    addL(mom, "Oh, that's a shame. I think you'd make a cute couple.");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "What in the world made you think so?");*/

    changeShowCharacter(nathan, angryFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 2);
    changeShowCharacter(nathan, neutralFace, cPX(1) + defpw/5, cPY(1), defpw, defph, 0, 1, 5);
    changeShowCharacter(catie, angryFace, cPX(1) - defpw/5, cPY(1), defpw, defph, 0, 1, 5);
    doWait(1);
    changeShowCharacter(protag, surpriseFace3);
    addL(unknown, "Can you keep it down? I'm trying to read.");
    doWait(1);
    changeShowCharacter(catie, surpriseFace);
    doWait(3);
    changeShowCharacter(catie, neutralFace2);
    addL(unknown, "...Who is that?");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "I'm Mary van Buren, Jonathan's classmate! Nice to meet you!");
    addL(unknown, "N-Nice to neet... meet you.");
    changeShowCharacter(protag, happyFace);
    addL(mary, "What's your name?");
    addL(unknown, "C-Ca... Catherine.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Can I call you 'Cat?'");
    changeShowCharacter(catie, surpriseFace);
    addL(catie, "Wha...");

    changeShowCharacter(catie, sadFace, cPX(1) - defpw/5, cPY(1), defpw, defph, 0, 1, 2);
    // changeShowCharacter(nathan, neutralFace, cPX(1) + defpw/5, cPY(1), defpw, defph, 0, 1, 2);
    changeShowCharacter(catie, surpriseFace2, cPX(1.5), cPY(1.5), defpw*1.5, defph*1.5, 0, 1, 5);

    changeShowCharacter(nathan, neutralFace2);
    changeShowCharacter(protag, happyFace3);
    addL(mary, "You're so cute! You're like smaller, less crabby Jonathan!");
    doAnim(catie, 3);
    addL(catie, "Eek!");
    changeShowCharacter(catie, sadFace);
    addL(catie, "Stop! Don't hug me!");
    addL(mary, "Cute, cute, cute!");
    addL(catie, "Don't rub your cheeks against me!");
    changeShowCharacter(catie, angryFace);
    addL(catie, "Nate, help!");
    addL(nathan, "Huh, that neighbor already has his Christmas decorations up.");
    addL(catie, "Traitor!");
    break;
  case scene0_1_2_2:
    changeShowCharacter(protag, happyFace2);
    changeShowCharacter(nathan, neutralFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    addL(mary, "Yes, we've been dating for over a month now!");
    changeShowCharacter(nathan, angryFace);
    addL(mom, "Well, that puts a burden off my shoulders! Nate's never brought a girl home, so I was worried he'd turn into an old bachelor.");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "That won't happen on my watch! He said he's going to marry me as soon as we graduate!");
    addL(nathan, "I never said that, and we aren't dating.");
    addL(mom, "Please don't be offended. He's always been like that.");
    changeShowCharacter(protag, happyFace);
    addL(mary, "Far from it. That's one of his charms.");
    addL(nathan, "I'm going to kick you out.");
    break;
  case scene0_1_1_1:
    changeShowCharacter(protag, sadFace);
    changeShowCharacter(nathan, angryFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    addL(mary, "I'll buy the eggs. I don't want my mom to yell at me.");
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "That's a wise choice.");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Good afternoon! I'd like to buy these eggs.");
    addL(clerk, "Will you pay with cash or credit card?");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "I'm paying with cash. Just a second.");
    doAnim(protag, 2);
    addL(none, "*fumble* *fumble*");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Huh?");
    doAnim(protag, 2);
    addL(none, "*fumble* *fumble* *fumble*");
    changeShowCharacter(protag, surpriseFace);
    addL(mary, "Huh? Where is it?");
    doAnim(protag, 2);
    addL(none, "*fumble* *fumble*\n*fumble* *fumble*");
    addL(nathan, ".......");
    changeShowCharacter(protag, surpriseFace3);
    addL(nathan, "Excuse me. We're taking this as well.");
    changeShowCharacter(protag, neutralFace);
    addL(none, "............");
    addL(clerk, "Have a good afternoon!");
    changeBackground(bgStreet2, 2);
    changeShowCharacter(nathan, neutralFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    changeShowCharacter(protag, sadFace);
    addL(mary, "Sigh... That was scary.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Thanks, Jonathan. I'll give you the money back when next week.");
    addL(nathan, "Okay.");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "Well, then, as thanks...");
    addChoice(2, "Sing a song", "Do a hand stand");
    break;
  case scene0_1_1_2:
    changeShowCharacter(protag, sadFace);
    changeShowCharacter(nathan, angryFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    addL(mary, "Sorry, Mom, but I love ramen too much.");
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "You can buy both, you know.");
    addL(mary, "But then my love for ramen will seem insincere!");
    addL(nathan, "...Who cares?");
    addL(mary, "Nissin Foods.");
    addL(nathan, "Is that a fact?");
    changeShowCharacter(protag, happyFace);
    addL(mary, "What's your favorite brand?");
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "I don't have one.");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "I guess I'll get this one, then.");
    
    changeBackground(bgStreet2, 2);
    changeShowCharacter(nathan, angryFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Look! Isn't the sunset beautiful?");
    addL(nathan, ".........");
    changeShowCharacter(protag, sadFace);
    addL(mary, "What's with the face?");
    addL(nathan, "That's just what my face looks like.");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Why are you making that expression?");
    addL(nathan, "Because I'm carrying twenty packets of ramen for a stranger.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "I'm not a stranger! Besides, didn't I tell you you can take two of them?");
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "I don't like soy sauce...");
    addL(mary, "Why didn't you say that earlier? Then I would've gotten the other flavors.");
    addL(nathan, "I don't like instant ramen...");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "What do you like?");
    addL(nathan, "Tuna.");
    addL(mary, "What else?");
    addL(nathan, "Peanut butter.");
    addL(mary, "What else?");
    addL(nathan, "Cheese.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Then I'll make you a tuna-\npeanut-butter-cheese sandwich!");
    addL(nathan, "..........");
    addL(nathan, "That sounds delicious.");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Right?");
    break;
  case scene0_1_1_1_1:
    changeShowCharacter(protag, happyFace2);
    changeShowCharacter(nathan, neutralFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    addL(mary, "I'm going to write and sing you a custom theme song!");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "What?");
    changeShowCharacter(protag, happyFace3);
    changeShowCharacter(nathan, neutralFace);
    addL(mary, "Have you seen him?\nJonathan! ♪");
    addL(mary, "Have you heard of him?\nJonathan! ♪");
    changeShowCharacter(protag, sadFace);
    addL(mary, "He's sleep-deprived! ♪\nHe's below-average height! ♪\nHe's my classmate! ♪");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "If you were to describe him by three feelings, it would be... ♪");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Justice, love, and friendship! ♪");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "That's just Mazinger Z's ending song with worse lyrics.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "It's hard to come up with original lyrics.");
    break;
  case scene0_1_1_1_2:
    changeShowCharacter(protag, happyFace2);
    changeShowCharacter(nathan, neutralFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    addL(mary, "I'm going to do a hand stand!");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "I don't think that's a good idea.");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Why?");
	changeShowCharacter(nathan, neutralFace);
	addL(nathan, "For... gravity reasons...");
    addL(mary, "Gravity?");
	addL(nathan, "Gravity is a force that's responsible for...");
	changeShowCharacter(protag, neutralFace2);
	addL(mary, "*snore*");
	changeShowCharacter(nathan, angryFace);
	addL(nathan, "...........");
    addL(nathan, "You're wearing a skirt.");
    changeShowCharacter(protag, mairiFace);
    addL(mary, "Oh! That's what you meant. Never mind, then.");
	addL(nathan, "......");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "What's some other way I could show my gratitude?");
    changeShowCharacter(nathan, neutralFace);
    addL(nathan, "I don't think you need to do anything.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "I see, so just my presence is already enough thanks to you!");
    changeShowCharacter(nathan, angryFace);
    addL(nathan, "Nobody said that.");
    addL(mary, "He-he-he.");
    changeShowCharacter(nathan, happyFace);
    addL(nathan, "...Good grief.");
    changeBackground(bgStreet1Evening, 3);
    changeShowCharacter(nathan, neutralFace);
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Oh, my house is that way.");
    addL(nathan, "I'll see you later, then.");
    changeShowCharacter(protag, happyFace);
    addL(mary, "Bye! See you at school!");
    addL(nathan, "Later.");
    changeShowCharacter(nathan, neutralFace, cPX(), cPY(), defpw, defph, 0, 1, 2);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "La-la-la! ♪\n Going home! ♪");
    break;
  }
}

void Cutscene::maryCatieScript() {
  switch(sceneID) {
  case scene0:
    changeShowCharacter(protag, happyFace2);
    changeBackground(bgLivingRoom, 2);
    addL(mary, "I'm back from school, Mom!");
    addL(mom, "Oh, Molly, thank goodness you're here. Can you do me a favour?");
    addL(mom, "I forgot to buy eggs for today's supper. Can you go buy them for me?");
    // changeShowCharacter(protag, angryFace);
    addChoice(2, "Sure", "No");
    break;
  case scene0_2:
    changeShowCharacter(protag, sadFace);
    addL(mary, "I don't want to.");
    addL(mom, "Then we're having omelettes without eggs for today's supper.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Okay!");
    addL(mary, "...");
    changeShowCharacter(protag, surpriseFace);
    addL(mary, "What?!");
    break;
  case scene0_1:
    changeShowCharacter(protag, happyFace3);
     changeShowCharacter(catie, neutralFace2, cPX(0.75)-defpw/5, cPY(0.75), defpw*0.75, defph*0.75, 0, 0, -1);
    addL(mary, "Sure!");
    changeBackground(bgStreet1, 2);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "La-la-la! ♪\n Going to the grocery store! ♪\n In the sunshine! ♪");
    changeShowCharacter(catie, neutralFace2, cPX(0.75)-defpw/5, cPY(0.75), defpw*0.75, defph*0.75, 0, 1, 5);
    changeShowCharacter(catie, neutralFace2, cPX(0.75)-defpw/5, cPY(0.75), defpw*0.75, defph*0.75, 0, 1, 2);
    addL(mary, "Oh, it's Cat!!");
    changeShowCharacter(catie, neutralFace2, cPX(1), cPY(1), defpw, defph, 0, 1, 2);
    changeShowCharacter(catie, neutralFace2, cPX(1), cPY(1), defpw, defph, 0, 1, 3);
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Good morning, cutie!");
	changeShowCharacter(catie, surpriseFace);
	doAnim(catie, 3);
    addL(catie, "Ah!?");
    changeShowCharacter(catie, sadFace);
    addL(catie, "Oh, M-Moll, it's you...\nI thought it was a pervert...");
	changeShowCharacter(protag, happyFace2);
    addL(mary, "Mary van Buren's the name, speed's my game!");
    addL(catie, "Huh? Ah, y-yeah...");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Meow!");
    changeShowCharacter(catie, neutralFace2);
    addL(catie, "...?");
    addL(mary, "Meow!");
	changeShowCharacter(catie, neutralFace);
    addL(catie, "..........");
    addL(mary, "Meow!");
	addL(catie, "!!!");
	changeShowCharacter(catie, happyFace);
    addL(catie, "M-Meow!");
	
	changeShowCharacter(catie, happyFace, cPX(1) - defpw/5, cPY(1), defpw, defph, 0, 1, 2);
    changeShowCharacter(catie, surpriseFace2, cPX(1.5), cPY(1.5), defpw*1.5, defph*1.5, 0, 1, 5);
    changeShowCharacter(protag, happyFace3);
	doAnim(catie, 3);
    addL(catie, "Eek!");
    addL(mary, "That was the cutest meow I've ever heard!");
    changeShowCharacter(catie, neutralFace2);
    addL(catie, "D-don't hug me so tight! It hurts!");
    addChoice(2, "Say it again!", "Actually, nevermind.");
    break;
  case scene0_1_1:
    changeShowCharacter(protag, happyFace);
    changeShowCharacter(catie, neutralFace2, cPX(1.5), cPY(1.5), defpw*1.5, defph*1.5, 0, 1);
    addL(mary, "I need to hear it again!");
	changeShowCharacter(catie, neutralFace);
    addL(catie, "I-I can't. It's too embarrassing...");
    changeShowCharacter(protag, sadFace);
    addL(mary, "Please! I'm going to die!");
	changeShowCharacter(catie, surpriseFace);
    addL(catie, "Huh?! D-Die?!");
    addL(mary, "Quick! I can feel the life draining out of my body!");
	changeShowCharacter(catie, sadFace);
    addL(catie, "W-Wait! Don't die! I'll say it!");
	addL(mary, ".........");
	changeShowCharacter(catie, neutralFace2);
	addL(catie, ".........");
	changeShowCharacter(catie, happyFace2);
	addL(catie, "M-Meow.");
    changeShowCharacter(protag, happyFace3);
	changeShowCharacter(catie, surpriseFace);
	doAnim(catie, 3);
    addL(mary, "Ahahahaaa! Cute, cute, cute!");
	changeShowCharacter(catie, sadFace);
    addL(catie, "?! Weren't you dying?!");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Yes, but thy cuteness cureth the sick and the blind!");
    changeShowCharacter(catie, neutralFace2);
    addL(catie, "...What were you sick of?");
	changeShowCharacter(protag, happyFace3);
    addL(mary, "Acute cuteness deficiency!");
    changeShowCharacter(catie, angryFace2);
	changeShowCharacter(protag, happyFace2);
    addL(catie, "............");
    changeShowCharacter(protag, mairiFace);
    addL(mary, "............");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Acute cuteness deficiency!");
	changeShowCharacter(catie, angryFace3);
    addL(catie, "I heard you!");
	changeShowCharacter(protag, surpriseFace);
    addL(mary, "Eek!");
	
	changeShowCharacter(catie, neutralFace2, cPX(1.5), cPY(1.5), defpw*1.5, defph*1.5, 0, 1, 2);
	changeShowCharacter(catie, angryFace, cPX(1), cPY(1), defpw, defph, 0, 1, 5);
	changeShowCharacter(protag, mairiFace);
		
    addL(catie, "Are you always like this?\nNow why did Nate...");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Nat? What'd he say about me?");
	changeShowCharacter(catie, neutralFace);
    addL(catie, "A-Ah? N-Nothing, forget what I just said.");
    addChoice(2, "WHAT DID HE SAY?!?!!!", "Never mind");
    break;
  case scene0_1_2:
    changeShowCharacter(protag, neutralFace);
    changeShowCharacter(catie, neutralFace, cPX(), cPY(), defpw, defph, 0);
    addL(mary, "George Washington!");
    addL(catie, "No, George Washington didn't produce any literature of note.");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "But it was pretty close, wasn't it?");
    addL(catie, "No.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "But he was a great president.");
    addL(catie, "That's not relevant.");
    addL(mary, "He freed the slaves.");
    /*addL(catie, "That was Abraham Lincoln.");
    changeShowCharacter(protag, mairiFace);
    addL(mary, "Piers... P-Pake... Pearson...");
    changeShowCharacter(catie, neutralFace);*/
    addL(catie, "How many hours do you study a day?");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "About fifteen minutes?");
    addL(catie, "Are you fine with that?");
    addL(mary, "Are you worried about me?");
    addL(catie, "Of course I am. You're worse than my sister.");
    changeShowCharacter(protag, surpriseFace3);
    addL(mary, "You have a sister? Is she cute?");
    changeShowCharacter(catie, neutralFace2);
    addL(catie, "She's not cute.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "I'll go meet her now!");
    changeShowCharacter(catie, angryFace);
    addL(catie, "I said she's not cute!");
    
    changeBackground(bgLivingRoom, 2);
    changeShowCharacter(catie, neutralFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Excuse me! Anyone at home?");
    addL(mom, "Oh, are you back already, Nate?");
    addL(mom, "My word, is that your girlfriend?");
    addChoice(2, "We're friends", "We've been dating for a month");
    break;
  case scene0_1_2_1:
    changeShowCharacter(protag, happyFace);
    changeShowCharacter(catie, neutralFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    addL(mary, "We're friends.");
    changeShowCharacter(catie, angryFace);
    addL(catie, "Classmates.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "I came to your house, so that means we're friends now.");
    changeShowCharacter(catie, angryFace);
    addL(catie, "No, it doesn't.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "Why did you invite me to your house if you don't think of me as a friend?");
    addL(catie, "I didn't invite you.");
    /*changeShowCharacter(protag, surpriseFace);
    addL(mary, "Wait, don't send me to jail! I'm sorry!");
    addL(mom, "Oh, that's a shame. I think you'd make a cute couple.");
    changeShowCharacter(catie, angryFace);
    addL(catie, "What in the world made you think so?");*/

    changeShowCharacter(catie, angryFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 2);
    changeShowCharacter(catie, neutralFace, cPX(1) + defpw/5, cPY(1), defpw, defph, 0, 1, 5);
    changeShowCharacter(catie, angryFace, cPX(1) - defpw/5, cPY(1), defpw, defph, 0, 1, 5);
    doWait(1);
    changeShowCharacter(protag, surpriseFace3);
    addL(unknown, "Can you keep it down? I'm trying to read.");
    doWait(1);
    changeShowCharacter(catie, surpriseFace);
    doWait(3);
    changeShowCharacter(catie, neutralFace2);
    addL(unknown, "...Who is that?");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "I'm Mary van Buren, Jocatie's classmate! Nice to meet you!");
    addL(unknown, "N-Nice to neet... meet you.");
    changeShowCharacter(protag, happyFace);
    addL(mary, "What's your name?");
    addL(unknown, "C-Ca... Catherine.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Can I call you 'Cat?'");
    changeShowCharacter(catie, surpriseFace);
    addL(catie, "Wha...");

    changeShowCharacter(catie, sadFace, cPX(1) - defpw/5, cPY(1), defpw, defph, 0, 1, 2);
    // changeShowCharacter(catie, neutralFace, cPX(1) + defpw/5, cPY(1), defpw, defph, 0, 1, 2);
    changeShowCharacter(catie, surpriseFace2, cPX(1.5), cPY(1.5), defpw*1.5, defph*1.5, 0, 1, 5);

    changeShowCharacter(catie, neutralFace2);
    changeShowCharacter(protag, happyFace3);
    addL(mary, "You're so cute! You're like smaller, less crabby Jocatie!");
    doAnim(catie, 3);
    addL(catie, "Eek!");
    changeShowCharacter(catie, sadFace);
    addL(catie, "Stop! Don't hug me!");
    addL(mary, "Cute, cute, cute!");
    addL(catie, "Don't rub your cheeks against me!");
    changeShowCharacter(catie, angryFace);
    addL(catie, "Nate, help!");
    addL(catie, "Huh, that neighbor already has his Christmas decorations up.");
    addL(catie, "Traitor!");
    break;
  case scene0_1_2_2:
    changeShowCharacter(protag, happyFace2);
    changeShowCharacter(catie, neutralFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    addL(mary, "Yes, we've been dating for over a month now!");
    changeShowCharacter(catie, angryFace);
    addL(mom, "Well, that puts a burden off my shoulders! Nate's never brought a girl home, so I was worried he'd turn into an old bachelor.");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "That won't happen on my watch! He said he's going to marry me as soon as we graduate!");
    addL(catie, "I never said that, and we aren't dating.");
    addL(mom, "Please don't be offended. He's always been like that.");
    changeShowCharacter(protag, happyFace);
    addL(mary, "Far from it. That's one of his charms.");
    addL(catie, "I'm going to kick you out.");
    break;
  case scene0_1_1_1:
    changeShowCharacter(protag, surpriseFace);
	changeShowCharacter(catie, neutralFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    addL(mary, "WHAT DID HE SAY?!?!!!!");
    changeShowCharacter(catie, neutralFace2);
    addL(catie, "...D-Do you really want to hear it?");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "Hmm, now that I think about it...");
	changeShowCharacter(catie, neutralFace);
    addL(catie, "...Well, he says you're annoying.");
    changeShowCharacter(protag, surpriseFace);
    addL(mary, "What?");
    addL(catie, "...And that you smell bad.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "......");
	changeShowCharacter(catie, happyFace);
    addL(catie, "Also, your hairstyle is weird.");
	addL(mary, "It's not... it's cute...");
	changeShowCharacter(catie, neutralFace);
	addL(catie, "It's weird...");
	addL(mary, "...... *sob*");
	changeShowCharacter(catie, neutralFace);
	addL(catie, "......?");
	doAnim(protag, 4);
	addL(mary, "...... *sob* *sob*");
	changeShowCharacter(catie, neutralFace2);
	doAnim(protag, 4);
	addL(catie, "...?!?!?!");
	changeShowCharacter(catie, happyFace2);
	doAnim(protag, 4);
	addL(catie, "B-But he also said...!");
	addL(mary, "Thank you, Cat. I've heard enough.");
	changeShowCharacter(catie, sadFace);
	addL(catie, "N-No, wait, i-it's not...");
	addL(mary, "There's only one thing left to do now.");

    addChoice(2, "Commit seppuku!", "Cut my hair short!");
    break;
  case scene0_1_1_2:
    changeShowCharacter(protag, sadFace);
    changeShowCharacter(catie, angryFace, cPX(1.25), cPY(1.25), defpw*1.25, defph*1.25, 0, 1, 1);
    addL(mary, "Sorry, Mom, but I love ramen too much.");
    changeShowCharacter(catie, neutralFace);
    addL(catie, "You can buy both, you know.");
    addL(mary, "But then my love for ramen will seem insincere!");
    addL(catie, "...Who cares?");
    addL(mary, "Nissin Foods.");
    addL(catie, "Is that a fact?");
    changeShowCharacter(protag, happyFace);
    addL(mary, "What's your favorite brand?");
    changeShowCharacter(catie, neutralFace);
    addL(catie, "I don't have one.");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "I guess I'll get this one, then.");
    
    changeBackground(bgStreet2, 2);
    changeShowCharacter(catie, angryFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Look! Isn't the sunset beautiful?");
    addL(catie, ".........");
    changeShowCharacter(protag, sadFace);
    addL(mary, "What's with the face?");
    addL(catie, "That's just what my face looks like.");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Why are you making that expression?");
    addL(catie, "Because I'm carrying twenty packets of ramen for a stranger.");
    changeShowCharacter(protag, sadFace);
    addL(mary, "I'm not a stranger! Besides, didn't I tell you you can take two of them?");
    changeShowCharacter(catie, neutralFace);
    addL(catie, "I don't like soy sauce...");
    addL(mary, "Why didn't you say that earlier? Then I would've gotten the other flavors.");
    addL(catie, "I don't like instant ramen...");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "What do you like?");
    addL(catie, "Tuna.");
    addL(mary, "What else?");
    addL(catie, "Peanut butter.");
    addL(mary, "What else?");
    addL(catie, "Cheese.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "Then I'll make you a tuna-\npeanut-butter-cheese sandwich!");
    addL(catie, "..........");
    addL(catie, "That sounds delicious.");
    changeShowCharacter(protag, happyFace3);
    addL(mary, "Right?");
    break;
  case scene0_1_1_1_1:
    changeShowCharacter(protag, sadFace);
    changeShowCharacter(catie, sadFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    addL(mary, "I'm going to commit sudoku!");
    changeShowCharacter(catie, neutralFace);
    addL(catie, "...Do you mean seppuku?");
    changeShowCharacter(protag, surpriseFace);
    addL(mary, "What's seppuku?");
    addL(catie, "Seppuku is a method of ritual suicide that was...");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "*snore*");
    changeShowCharacter(catie, surpriseFace);
    addL(catie, "............");
	changeShowCharacter(catie, neutralFace2);
    addL(catie, "Crisis... averted...");
    break;
  case scene0_1_1_1_2:
    changeShowCharacter(protag, happyFace2);
    changeShowCharacter(catie, neutralFace, cPX(), cPY(), defpw, defph, 0, 1, 1);
    addL(mary, "I'm going to do a hand stand!");
    changeShowCharacter(catie, angryFace);
    addL(catie, "I don't think that's a good idea.");
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Why?");
    addL(catie, "For... gravity reasons...");
	addL(mary, "What's gravity?");
	addL(catie, ".........");
    changeShowCharacter(protag, mairiFace);
    addL(mary, "Oh, right. Never mind, then.");
    changeShowCharacter(protag, neutralFace2);
    addL(mary, "What's some other way I could show my gratitude?");
    changeShowCharacter(catie, neutralFace);
    addL(catie, "I don't think you need to do anything.");
    changeShowCharacter(protag, happyFace2);
    addL(mary, "I see, so just my presence is already enough thanks to you!");
    changeShowCharacter(catie, angryFace);
    addL(catie, "Nobody said that.");
    addL(mary, "He-he-he.");
    changeShowCharacter(catie, happyFace);
    addL(catie, "...Good grief.");
    changeBackground(bgStreet1Evening, 3);
    changeShowCharacter(catie, neutralFace);
    changeShowCharacter(protag, neutralFace);
    addL(mary, "Oh, my house is that way.");
    addL(catie, "I'll see you later, then.");
    changeShowCharacter(protag, happyFace);
    addL(mary, "Bye! See you at school!");
    addL(catie, "Later.");
    changeShowCharacter(catie, neutralFace, cPX(), cPY(), defpw, defph, 0, 1, 2);
    changeShowCharacter(protag, happyFace2);
    addL(mary, "La-la-la! ♪\n Going home! ♪");
    break;
  }
}